package main

import (
	"context"
	"fmt"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

func getEnv(key string, def string) string {
	v := os.Getenv(key)
	if v == "" {
		return def
	}
	return v
}

func main() {
	dbURL := getEnv("DATABASE_URL", "")
	if dbURL == "" {
		dbURL = "postgres://careerscout:careerscout_dev_password@127.0.0.1:5432/careerscout"
	}

	ctx := context.Background()
	pool, err := pgxpool.New(ctx, dbURL)
	if err != nil {
		log.Fatalf("db connect failed: %v", err)
	}
	defer pool.Close()

	rows, err := pool.Query(ctx, "SELECT url FROM raw_captures WHERE label = 1")
	if err != nil {
		log.Fatalf("query failed: %v", err)
	}

	domainsMap := make(map[string]bool)
	segmentsMap := make(map[string]int)

	for rows.Next() {
		var u string
		if err := rows.Scan(&u); err != nil {
			continue
		}
		parsed, err := url.Parse(u)
		if err != nil {
			continue
		}

		// Extract domain (strip subdomains like api. lever. etc roughly, or just keep host)
		// Usually we keep the full host for ATS comparison in the classifier
		host := parsed.Hostname()
		// Basic normalization (remove www.)
		host = strings.TrimPrefix(host, "www.")
		domainsMap[host] = true

		// Extract path segments
		segs := strings.Split(parsed.Path, "/")
		for _, s := range segs {
			if s != "" {
				// Don't capture numbers, UUIDs, or highly variable parts
				// A simple heuristic: if it contains only letters and hyphens
				isAlpha := true
				for _, r := range s {
					if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && r != '-' && r != '_' {
						isAlpha = false
						break
					}
				}
				if isAlpha && len(s) > 2 {
					segmentsMap["/"+s]++
				}
			}
		}
	}
	rows.Close()

	var domains []string
	for d := range domainsMap {
		domains = append(domains, `"`+d+`"`)
	}
	sort.Strings(domains)

	var segments []string
	for s, count := range segmentsMap {
		if count > 1 {
			segments = append(segments, `"`+s+`"`)
		}
	}
	sort.Strings(segments)

	content := fmt.Sprintf(`// Code generated by cmd/extract_patterns. DO NOT EDIT.
package tier2_v3

// GeneratedATSDomains contains domains extracted from confirmed (label=1) job API captures.
var GeneratedATSDomains = []string{
	%s,
}

// GeneratedJobPathSegments contains path segments extracted from confirmed job API captures
// that appeared more than once.
var GeneratedJobPathSegments = []string{
	%s,
}
`, strings.Join(domains, ",\n\t"), strings.Join(segments, ",\n\t"))

	outPath := filepath.Join("internal", "tier2_v3", "generated_patterns.go")
	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		log.Fatalf("Failed to write generated file: %v", err)
	}

	fmt.Printf("Successfully extracted %d domains and %d path segments to %s\n", len(domains), len(segments), outPath)
}
