apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: careerscout
    uid: PostgreSQL
    secureJsonData:
      password: "careerscout_dev_password"
    jsonData:
      database: careerscout
      sslmode: "disable"
