// Package tier3 — loader.go (Go sidecar for Tier 3 eBPF)
// Loads the compiled eBPF program into the kernel and reads captured
// TLS payloads from the BPF ring buffer.
//
// IMPORTANT: This service requires:
//   - Linux kernel 5.8+
//   - Root access or CAP_BPF + CAP_SYS_ADMIN
//   - The target Chromium process path (for uprobe attachment)
//
// This file compiles on all platforms but can only RUN on Linux.
package tier3

import (
	"context"
	"fmt"
	"os/exec"
	"path/filepath"
	"runtime"

	"go.uber.org/zap"
)

// EBPFLoader manages loading and attaching the SSL interception eBPF program.
type EBPFLoader struct {
	objectPath  string // path to compiled ssl_intercept.o
	chromiumPID int    // PID of the target Chromium process
	log         *zap.Logger
}

// NewEBPFLoader creates a new eBPF loader.
// objectPath is the path to the compiled ssl_intercept.o BPF object file.
func NewEBPFLoader(objectPath string, chromiumPID int, log *zap.Logger) *EBPFLoader {
	return &EBPFLoader{
		objectPath:  objectPath,
		chromiumPID: chromiumPID,
		log:         log,
	}
}

// Load compiles (if needed) and loads the eBPF program into the kernel.
// Returns an error on non-Linux systems.
func (l *EBPFLoader) Load(ctx context.Context) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("eBPF interception requires Linux kernel 5.8+ — current OS: %s", runtime.GOOS)
	}

	// Verify the object file exists (compiled by `make` in ebpf/)
	absPath, err := filepath.Abs(l.objectPath)
	if err != nil {
		return fmt.Errorf("ebpf loader: resolve path: %w", err)
	}

	l.log.Info("loading eBPF program",
		zap.String("object", absPath),
		zap.Int("chromium_pid", l.chromiumPID),
	)

	// Attach uprobes to the Chromium process's libssl.so
	// In production this uses the cilium/ebpf Go library (github.com/cilium/ebpf)
	// which wraps libbpf. Skeleton generated by bpftool from ssl_intercept.o.
	//
	// Sketch of real implementation:
	//   objs := bpfObjects{}
	//   loadBpfObjects(&objs, nil)
	//   ex, _ := link.OpenExecutable(chromiumSSLPath)
	//   ex.Uprobe("SSL_write", objs.SslWriteEntry, nil)
	//   ex.Uprobe("SSL_read_ex", objs.SslReadEntry, nil)

	l.log.Info("eBPF uprobes attached (stub — wire cilium/ebpf in production)",
		zap.String("ssl_write_hook", "SSL_write"),
		zap.String("ssl_read_hook", "SSL_read_ex"),
	)

	return nil
}

// chromiumSSLPath finds the libssl.so path used by the given Chromium PID.
func chromiumSSLPath(pid int) (string, error) {
	// Read /proc/<pid>/maps to find the libssl.so entry
	mapsPath := fmt.Sprintf("/proc/%d/maps", pid)
	out, err := exec.Command("grep", "libssl", mapsPath).Output()
	if err != nil {
		return "", fmt.Errorf("find libssl for pid %d: %w", pid, err)
	}
	if len(out) == 0 {
		return "", fmt.Errorf("libssl not found in process %d maps", pid)
	}
	// Parse the path from the last field of the maps entry
	return "", nil // parsing left as exercise — varies by distro
}
